add_parent_workflow_mini
small version excluding codeql and ubuntu

Signed-off-by: Erik Hu <135733975+Erikhu1@users.noreply.github.com>

diff --git a/.github/workflows/parent-workflow.yml b/.github/workflows/parent-workflow.yml
--- a/.github/workflows/parent-workflow.yml
+++ b/.github/workflows/parent-workflow.yml
@@ -1,11 +1,12 @@
 name: Parent Workflow
-#test 
+
 on: 
   pull_request:
   push: 
     branches:
       - develop
       - main
+      - copy_of_main
 
 permissions:
   contents: write
@@ -33,34 +34,34 @@ jobs:
     with:
       artifact_id: "test_trudag_extensions-${{ github.sha }}"
 
-  codeql:
-    name: Run Codeql analysis Workflow
-    uses: ./.github/workflows/codeql-analysis.yml
-    with:
-      artifact_id: "codeql-${{ github.sha }}"
+  #codeql:
+  #  name: Run Codeql analysis Workflow
+  #  uses: ./.github/workflows/codeql-analysis.yml
+  #  with:
+  #    artifact_id: "codeql-${{ github.sha }}"
 
-  ubuntu:
-    name: Run Ubuntu Workflow
-    needs: [codeql] # Error if CodeQL and Ubuntu triggered at the same time due to conflicting priorities
-    uses: ./.github/workflows/ubuntu.yml
-    with:
-      artifact_id: "ubuntu-${{ github.sha }}"
+  #ubuntu:
+  #  name: Run Ubuntu Workflow
+  #  needs: [codeql] # Error if CodeQL and Ubuntu triggered at the same time due to conflicting priorities
+  #  uses: ./.github/workflows/ubuntu.yml
+  #  with:
+  #    artifact_id: "ubuntu-${{ github.sha }}"
 
   dependency_review:
     name: Run dependency_review Workflow
+    if: ${{ github.event_name == 'pull_request' }} 
     uses: ./.github/workflows/dependency-review.yml
     with:
       artifact_id: "dependency_review-${{ github.sha }}"
 
-
-  collect-and-deploy:
-    name: "Collect Results & Deploy"
-    needs: [labeler, check_amalgamation, test_trudag_extensions, codeql, dependency_review, ubuntu]
+  collect-and-deploy-pr:
+    name: "Collect Results & Deploy (PR)"
+    if: github.event_name == 'pull_request'
+    needs: [labeler, check_amalgamation, test_trudag_extensions, dependency_review]
     runs-on: ubuntu-latest
-    if: always() # Run even if some jobs fail
     strategy:
       matrix:
-        target: [labeler, check_amalgamation, test_trudag_extensions, codeql, dependency_review, ubuntu] 
+        target: [labeler, check_amalgamation, test_trudag_extensions, dependency_review]
 
     steps:
       - name: Checkout code
@@ -79,7 +80,47 @@ jobs:
           echo "✅ Child workflows completed successfully!" 
         env:
           current_workflow: ${{ matrix.target }}
- 
+
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: "${{ matrix.target }}-${{ github.sha }}"
+          path: artifacts/
+
+      - name: Deployment simulation
+        run: |
+          echo "🚀 Simulating deployment..."
+          sleep 2
+          echo "✅ Deployment completed successfully!"
+
+
+  collect-and-deploy-non-pr:
+    name: "Collect Results & Deploy (Non-PR)"
+    if: github.event_name != 'pull_request'
+    needs: [labeler, check_amalgamation, test_trudag_extensions]  # no dependency_review if non PR
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        target: [labeler, check_amalgamation, test_trudag_extensions]
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Check child workflow results 
+        run: |
+          echo "=== Checking Child Workflow Results ==="
+          result="${{ needs[matrix.target].result }}"
+          echo "${{ matrix.target }} workflow result: $result"
+
+          if [[ "$result" != "success" ]]; then
+            echo "❌ ${{ matrix.target }} workflow failed! Exiting..."
+            exit 1
+          fi
+          echo "✅ Child workflows completed successfully!" 
+        env:
+          current_workflow: ${{ matrix.target }}
+
       - name: Download artifacts
         uses: actions/download-artifact@v4
         with:
